### ISSUE TITLE
Timezone API - Allways return IPGeolocationError 'timeZoneName' must not be empty or null

### ISSUE THREAD

**Issue by davidAlvarezConsultia** [IPGeolocation/ip-geolocation-api-java-sdk#20]
Always I try to get the Timezone of an IP addres I'm fancing the same error exception: 

**io.ipgeolocation.api.exceptions.IPGeolocationError: 'timeZoneName' must not be empty or null**

Here is my sample code:
![image](https://github.com/IPGeolocation/ip-geolocation-api-java-sdk/assets/151620740/710a7b3e-12c6-4949-b619-9c9aff4c0f9f)

I've done it as you mention on the documentacion:

![image](https://github.com/IPGeolocation/ip-geolocation-api-java-sdk/assets/151620740/2c6ab68d-6aae-404c-8192-9116645c2df7)

What's the problem?

**Comment by davidAlvarezConsultia** [comment]
> Always I try to get the Timezone of an IP addres I'm fancing the same error exception:
> 
> **io.ipgeolocation.api.exceptions.IPGeolocationError: 'timeZoneName' must not be empty or null**
> 
> Here is my sample code: ![image](https://private-user-images.githubusercontent.com/151620740/336012888-710a7b3e-12c6-4949-b619-9c9aff4c0f9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTExMTUsIm5iZiI6MTcxNzQxMDgxNSwicGF0aCI6Ii8xNTE2MjA3NDAvMzM2MDEyODg4LTcxMGE3YjNlLTEyYzYtNDk0OS1iNjE5LTljOWFmZjRjMGY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMDMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzdiNjc1ZTdjMTVhMmUyNmE5YWI4ZGFmZTRhNjgxMTdkMzBiNDUwNTE5MWM1NzczMDcxNjM1YjE4MWNkZDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z5WtcrCYpFLf7PRNTGdz86mrnSUctcioAKWa2pQCmbE)
> 
> I've done it as you mention on the documentacion:
> 
> ![image](https://private-user-images.githubusercontent.com/151620740/336013108-2c6ab68d-6aae-404c-8192-9116645c2df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTExMTUsIm5iZiI6MTcxNzQxMDgxNSwicGF0aCI6Ii8xNTE2MjA3NDAvMzM2MDEzMTA4LTJjNmFiNjhkLTZhYWUtNDA0Yy04MTkyLTkxMTY2NDVjMmRmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMDMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDgxZmI5MDViZmY3MmQ5MGExOTA4NWQ5NjA4MGQxZWQxYjViOTViN2E4MGZmNDlmYjU5NDZmYWI0YWYxMDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nk4rvlLJ6yQEvdOg4ODZsFCpfQYFbVx7w_29SUFkogs)
> 
> What's the problem?
 Problem solved... I was trying the code from my local... so the IP was 127.0.0.1...
 
 Sorry

**Comment by DaudAhmadJF** [comment]
There seems to be no issue with your provided code. Let us know, if there's any thing else we can help you.
