### ISSUE TITLE
JsonSyntaxException when calling 'getGeolocation'

### ISSUE THREAD

**Issue by Leaghte** [IPGeolocation/ip-geolocation-api-java-sdk#8]
We receive the JsonSyntaxException when calling IPGeolocationAPI#getGeolocation. However the exception occurs randomly, not for every call. Here is the stack trace from our logs:

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.Gson.fromJson(Gson.java:939) ~[gson-2.8.5.jar:na]
    at com.google.gson.Gson.fromJson(Gson.java:892) ~[gson-2.8.5.jar:na]
    at com.google.gson.Gson.fromJson(Gson.java:841) ~[gson-2.8.5.jar:na]
    at com.google.gson.Gson.fromJson(Gson.java:813) ~[gson-2.8.5.jar:na]
    at io.ipgeolocation.api.IPGeolocationAPI.convertJSONStringToMap(IPGeolocationAPI.java:201) ~[ipgeolocation-1.0.11.jar:na]
    at io.ipgeolocation.api.IPGeolocationAPI.callAPIEndpoint(IPGeolocationAPI.java:157) ~[ipgeolocation-1.0.11.jar:na]
    at io.ipgeolocation.api.IPGeolocationAPI.getGeolocationResponse(IPGeolocationAPI.java:38) ~[ipgeolocation-1.0.11.jar:na]
    at io.ipgeolocation.api.IPGeolocationAPI.getGeolocation(IPGeolocationAPI.java:30) ~[ipgeolocation-1.0.11.jar:na]`.

We use latest IPGeolocation SDK version 1.0.11.

**Comment by eff-kay** [comment]
@ejaz-ahmed

**Comment by ejaz-ahmed** [comment]
@Leaghte which java version do you use? If possible, can you post code snippet that uses our SDK? Any steps/hints to reproduce are welcome.

**Comment by ipgeolocationdotio** [comment]
@Leaghte Can you provide the IP addresses on which exception occurred?

**Comment by Leaghte** [comment]
Sorry for the delayed reply.
@ejaz-ahmed We use OpenJDK11, and here is the snippet from the code:
![image](https://user-images.githubusercontent.com/7208681/82808960-51e7a600-9e8b-11ea-9b08-82f83e96b1e7.png)

@ipgeolocationdotio We currently do not log IP addresses. We will enable required logging and
I'll send you an IP address for which the exception occurs as soon as possible.

**Comment by MudassarTariq** [comment]
@Leaghte Have you been able to get the ip addresses for which you are getting this exception or has your issue was fixed as we didn't received any info from your end till yet.

**Comment by Leaghte** [comment]
@MudassarTariq After delving deeper into the issue, we discovered that it was not directly related to an IP address but rather to the data type of one of the fields in the Geolocation model. This field is returned as a JSON by the IP Geolocation server, and it had undergone a change, leading to an error during JSON deserialization into an object.

As this issue needed to be resolved promptly (since our production was affected by it), we opted to implement our own IP geolocation client.

**Comment by MudassarTariq** [comment]
@Leaghte Sorry for the inconvenience caused to you. I was asking for IpAddress to reproduce the issue because maybe the response of some specific ipAddresses contains that json that you've mentioned. Furthermore, we have updated data types in our sdk and the updated version is available on github so you can try that. Our team will further investigate the issue to solve it promptly if it hasn't yet. 
Regards
